image: docker:latest

stages:
- build
- push

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
  stage: build
  script:
    - docker build --target build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA .
  tags:
    - docker

push:
  stage: push
  script:
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$latest
  tags:
    - docker