apiVersion: v1
kind: Namespace
metadata:
  name: devops
  labels: 
    name: devops
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels: 
    name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
  labels: 
    name: stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels: 
    name: production